### ISSUE TITLE
util.puts is deprecated. use console.log instead

### ISSUE THREAD

**Issue by King-Ran** [somax/web-server-mock#2]
Hi,In the  recently ,i use wsm , i get error  info .
wsm 9000

----- error info ------
if need mockdata, put *.js file in ./mockdata/!
/usr/local/lib/node_modules/web-server-mock/web-server-mock.js:92
  util.puts('WSM ('+VERSION+') running at http://localhost:' + port + '/\n');
       ^

TypeError: util.puts is not a function
    at HttpServer.start (/usr/local/lib/node_modules/web-server-mock/web-server-mock.js:92:8)
    at main (/usr/local/lib/node_modules/web-server-mock/web-server-mock.js:49:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-server-mock/web-server-mock.js:431:1)
----- error info ------

My environment:

 node -v 
v12.14.1

I  researched in google site.
Maybe :
util.puts is deprecated. use console.log instead

**Comment by somax** [comment]
此项目已经停止维护，推荐你使用 https://github.com/typicode/json-server 

This project is no longer maintained, it is recommended that you use https://github.com/typicode/json-server
